In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

movies = pd.read_csv('tmdb_5000_movies.csv')
print(movies.shape)
movies.head(1)

(4803, 20)


budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                      homepage     id  \
0  http://www.avatarmovie.com/  19995   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   

  original_title                                           overview  \
0         Avatar  In the 22nd century, a paraplegic Marine is di...   

   popularity                               production_companies  \
0  150.437577  [{"name": "Ingenious Film Partners", "id": 289...   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   

                       tagline   title  vote_average  vote_count  
0  Enter the World of Pandora.  Avatar           7.2       11800

In [3]:
movies_df = movies[['id','title','genres','vote_average','vote_count','popularity','keywords','overview']]

In [4]:
display(movies_df[['genres','keywords']])
display(movies_df['genres'][0])

genres  \
0     [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1     [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2     [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3     [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4     [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
...                                                 ...   
4798  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4799  [{"id": 35, "name": "Comedy"}, {"id": 10749, "...   
4800  [{"id": 35, "name": "Comedy"}, {"id": 18, "nam...   
4801                                                 []   
4802                [{"id": 99, "name": "Documentary"}]   

                                               keywords  
0     [{"id": 1463, "name": "culture clash"}, {"id":...  
1     [{"id": 270, "name": "ocean"}, {"id": 726, "na...  
2     [{"id": 470, "name": "spy"}, {"id": 818, "name...  
3     [{"id": 849, "name": "dc comics"}, {"id": 853,...  
4     [{"id": 818, "name": "based on novel"}, {"id":...  
...                                                 ...  
4798  [{"id": 5616, "name": "united states\u2013mexi...  
4799                                                 []  
4800  [{"id": 248, "name": "date"}, {"id": 699, "nam...  
4801                                                 []  
4802  [{"id": 1523, "name": "obsession"}, {"id": 224...  

[4803 rows x 2 columns]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [5]:
# 0번째 영화의 장르는 액션+어드벤처+판타지+SF 이다.

In [6]:
pd.set_option('max_colwidth',1000)
movies_df[['genres','keywords']][:1]

genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          keywords  
0  [{"id": 1463, "name": "culture clash"}, {"id": 2964, "name": "future"}, {"id": 3386, "name": "space war"}, {"id": 3388, "name": "space colony"}, {"id": 3679, "name": "society"}, {"id": 3801, "name": "space travel"}, {"id": 9685, "name": "futuristic"}, {"id": 9840, "name": "romance"}, {"id": 9882, "name": "space"}, {"id": 9951, "name": "alien"}, {"id": 10148, "name": "tribe"}, {"id": 10158, "name": "alien planet"}, {"id": 10987, "name": "cgi"}, {"id": 11399, "name": "marine"}, {"id": 13065, "name": "soldier"}, {"id": 14643, "name": "battle"}, {"id": 14720, "name": "love affair"}, {"id": 165431, "name": "anti war"}, {"id": 193554, "name": "power relations"}, {"id": 206690, "name": "mind and soul"}, {"id": 209714, "name": "3d"}]

In [7]:
# ast 모듈의 literal_eval() 함수를 이용하면 이 문자열을 문자열이 의미하는 list[dict1, dict2] 객체로 만들 수 있다.
from ast import literal_eval
movies_df['genres'] = movies_df['genres'].apply(literal_eval)
movies_df['keywords'] = movies_df['keywords'].apply(literal_eval)

In [8]:
movies_df[['genres','keywords']][:1]

genres  \
0  [{'id': 28, 'name': 'Action'}, {'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 878, 'name': 'Science Fiction'}]   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          keywords  
0  [{'id': 1463, 'name': 'culture clash'}, {'id': 2964, 'name': 'future'}, {'id': 3386, 'name': 'space war'}, {'id': 3388, 'name': 'space colony'}, {'id': 3679, 'name': 'society'}, {'id': 3801, 'name': 'space travel'}, {'id': 9685, 'name': 'futuristic'}, {'id': 9840, 'name': 'romance'}, {'id': 9882, 'name': 'space'}, {'id': 9951, 'name': 'alien'}, {'id': 10148, 'name': 'tribe'}, {'id': 10158, 'name': 'alien planet'}, {'id': 10987, 'name': 'cgi'}, {'id': 11399, 'name': 'marine'}, {'id': 13065, 'name': 'soldier'}, {'id': 14643, 'name': 'battle'}, {'id': 14720, 'name': 'love affair'}, {'id': 165431, 'name': 'anti war'}, {'id': 193554, 'name': 'power relations'}, {'id': 206690, 'name': 'mind and soul'}, {'id': 209714, 'name': '3d'}]

In [9]:
# 차이가 없어 보이지만 이제 문자열이 아니라 실제 리스트 내부에 여러 장르 딕셔너리로 구성된 객체로 들어가 있는 상태이다.

In [10]:
movies_df['genres'] = movies_df['genres'].apply(lambda x : [ y['name'] for y in x]) 
movies_df['keywords'] = movies_df['keywords'].apply(lambda x : [ y['name'] for y in x])
movies_df[['genres','keywords']][:1]

genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   

                                                                                                                                                                                                                   keywords  
0  [culture clash, future, space war, space colony, society, space travel, futuristic, romance, space, alien, tribe, alien planet, cgi, marine, soldier, battle, love affair, anti war, power relations, mind and soul, 3d]

In [11]:
# 장르만 이용해서 카운터벡터화

from sklearn.feature_extraction.text import CountVectorizer

movies_df['genres_literal'] = movies_df['genres'].apply(lambda x: (' ').join(x))
count_vect = CountVectorizer(min_df=0, ngram_range=(1,2))
genre_mat = count_vect.fit_transform(movies_df['genres_literal'])

genre_mat.shape

(4803, 276)

In [12]:
movies_df[['genres','genres_literal']]

genres  \
0     [Action, Adventure, Fantasy, Science Fiction]   
1                      [Adventure, Fantasy, Action]   
2                        [Action, Adventure, Crime]   
3                  [Action, Crime, Drama, Thriller]   
4              [Action, Adventure, Science Fiction]   
...                                             ...   
4798                      [Action, Crime, Thriller]   
4799                              [Comedy, Romance]   
4800             [Comedy, Drama, Romance, TV Movie]   
4801                                             []   
4802                                  [Documentary]   

                                genres_literal  
0     Action Adventure Fantasy Science Fiction  
1                     Adventure Fantasy Action  
2                       Action Adventure Crime  
3                  Action Crime Drama Thriller  
4             Action Adventure Science Fiction  
...                                        ...  
4798                     Action Crime Thriller  
4799                            Comedy Romance  
4800             Comedy Drama Romance TV Movie  
4801                                            
4802                               Documentary  

[4803 rows x 2 columns]

In [13]:
# 코사인 유사도 계산
from sklearn.metrics.pairwise import cosine_similarity

genre_sim = cosine_similarity(genre_mat, genre_mat)
print(genre_sim.shape)
print(genre_sim[:2])

(4803, 4803)
[[1.         0.59628479 0.4472136  ... 0.         0.         0.        ]
 [0.59628479 1.         0.4        ... 0.         0.         0.        ]]


In [14]:
genre_sim_sorted_idx = genre_sim.argsort()[:,::-1] # 높은 순으로 정렬된 비교 행 위치 인덱스
genre_sim_sorted_idx[:2]

array([[   0, 3494,  813, ..., 3038, 3037, 2401],
       [ 262,    1,  129, ..., 3069, 3067, 2401]], dtype=int64)

In [15]:
# 참고
test = [1,5,10,4,3]
test_np = np.array(test)
test_idx = test_np.argsort() # 작은 값부터 순서대로 데이터의 index를 반환해줌
test_idx

array([0, 4, 3, 1, 2], dtype=int64)

In [16]:
# 장르 유사도에 따라 영화를 추천하는 함수 생성

def find_sim_movie(df, sorted_ind, title_name, top_n):
    
    # 인자로 입력된 movies_df DataFrame에서 'title' 컬럼이 입력된 title_name 값인 DataFrame추출
    title_movie = df[df['title'] == title_name]
    
    # title_named을 가진 DataFrame의 index 객체를 ndarray로 반환하고 
    # sorted_ind 인자로 입력된 genre_sim_sorted_ind 객체에서 유사도 순으로 top_n 개의 index 추출
    title_index = title_movie.index.values
    similar_indexes = sorted_ind[title_index, :(top_n)]
    
    # 추출된 top_n index들 출력. top_n index는 2차원 데이터 임. 
    #dataframe에서 index로 사용하기 위해서 1차원 array로 변경
    print(similar_indexes)
    similar_indexes = similar_indexes.reshape(-1)
    
    return df.iloc[similar_indexes]

In [17]:
find_sim_movie(movies_df, genre_sim_sorted_idx, 'The Godfather',10)

[[2731 1243 3636 1946 2640 4065 1847 4217  883 3866]]


id                                           title          genres  \
2731     240                          The Godfather: Part II  [Drama, Crime]   
1243     203                                    Mean Streets  [Drama, Crime]   
3636   36351                                   Light Sleeper  [Drama, Crime]   
1946   11699  The Bad Lieutenant: Port of Call - New Orleans  [Drama, Crime]   
2640     400         Things to Do in Denver When You're Dead  [Drama, Crime]   
4065  364083                                      Mi America  [Drama, Crime]   
1847     769                                      GoodFellas  [Drama, Crime]   
4217    9344                                            Kids  [Drama, Crime]   
883      640                             Catch Me If You Can  [Drama, Crime]   
3866     598                                     City of God  [Drama, Crime]   

      vote_average  vote_count  popularity  \
2731           8.3        3338  105.792936   
1243           7.2         345   17.002096   
3636           5.7          15    6.063868   
1946           6.0         326   17.339852   
2640           6.7          85    6.932221   
4065           0.0           0    0.039007   
1847           8.2        3128   63.654244   
4217           6.8         279   13.291991   
883            7.7        3795   73.944049   
3866           8.1        1814   44.356711   

                                                                                                                                                                                                                                                       keywords  \
2731                                                                                                            [italo-american, cuba, vororte, melancholy, praise, revenge, mafia, lawyer, blood, corrupt politician, bloody body of child, man punches woman]   
1243                                                                                                                                                                                               [epilepsy, protection money, secret love, money, redemption]   
3636                                                                                                                                                                                                 [suicide, drug dealer, redemption, addict, existentialism]   
1946                                                                                                                                                           [police brutality, organized crime, policeman, illegal drugs, murder investigation, corrupt cop]   
2640    [father son relationship, bounty hunter, boat, way of life, coffin, denver, godmother, paranoia, hitman, friendship, psychopath, revenge, murder, independent film, mafia, diner, blood, gangster, violence, illegal prostitution, extramarital affair]   
4065                                                                                                                                                                                                                               [new york state, hate crime]   
1847  [prison, based on novel, florida, 1970s, mass murder, irish-american, drug traffic, biography, based on true story, murder, organized crime, gore, mafia, gangster, new york city, extreme violence, violence, brooklyn new york city, crime epic, tampa]   
4217                                                                                                                                                                                                                                      [puberty, first time]   
883                                                                                                           [con man, biography, fbi agent, overhead camera shot, attempted jailbreak, engagement party, mislaid trust, bank fraud, inspired by a true story]   
3866                            

#### 위 함수 과정

In [18]:
title_movie = movies_df[movies_df['title'] == 'The Godfather']
title_movie

id          title          genres  vote_average  vote_count  \
3337  238  The Godfather  [Drama, Crime]           8.4        5893   

      popularity  \
3337  143.659698   

                                                                                                                                                     keywords  \
3337  [italy, love at first sight, loss of father, patriarch, organized crime, mafia, lawyer, italian american, crime family, rise to power, mob boss, 1940s]   

                                                                                                                                                                                                                                                                                                                 overview  \
3337  Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.   

     genres_literal  
3337    Drama Crime

In [19]:
title_index = title_movie.index.values

In [20]:
title_index

array([3337], dtype=int64)

In [21]:
similar_indexes = genre_sim_sorted_idx[title_index, :10]
similar_indexes

array([[2731, 1243, 3636, 1946, 2640, 4065, 1847, 4217,  883, 3866]],
      dtype=int64)

In [22]:
similar_indexes = similar_indexes.reshape(-1)

In [23]:
movies_df.iloc[similar_indexes]

id                                           title          genres  \
2731     240                          The Godfather: Part II  [Drama, Crime]   
1243     203                                    Mean Streets  [Drama, Crime]   
3636   36351                                   Light Sleeper  [Drama, Crime]   
1946   11699  The Bad Lieutenant: Port of Call - New Orleans  [Drama, Crime]   
2640     400         Things to Do in Denver When You're Dead  [Drama, Crime]   
4065  364083                                      Mi America  [Drama, Crime]   
1847     769                                      GoodFellas  [Drama, Crime]   
4217    9344                                            Kids  [Drama, Crime]   
883      640                             Catch Me If You Can  [Drama, Crime]   
3866     598                                     City of God  [Drama, Crime]   

      vote_average  vote_count  popularity  \
2731           8.3        3338  105.792936   
1243           7.2         345   17.002096   
3636           5.7          15    6.063868   
1946           6.0         326   17.339852   
2640           6.7          85    6.932221   
4065           0.0           0    0.039007   
1847           8.2        3128   63.654244   
4217           6.8         279   13.291991   
883            7.7        3795   73.944049   
3866           8.1        1814   44.356711   

                                                                                                                                                                                                                                                       keywords  \
2731                                                                                                            [italo-american, cuba, vororte, melancholy, praise, revenge, mafia, lawyer, blood, corrupt politician, bloody body of child, man punches woman]   
1243                                                                                                                                                                                               [epilepsy, protection money, secret love, money, redemption]   
3636                                                                                                                                                                                                 [suicide, drug dealer, redemption, addict, existentialism]   
1946                                                                                                                                                           [police brutality, organized crime, policeman, illegal drugs, murder investigation, corrupt cop]   
2640    [father son relationship, bounty hunter, boat, way of life, coffin, denver, godmother, paranoia, hitman, friendship, psychopath, revenge, murder, independent film, mafia, diner, blood, gangster, violence, illegal prostitution, extramarital affair]   
4065                                                                                                                                                                                                                               [new york state, hate crime]   
1847  [prison, based on novel, florida, 1970s, mass murder, irish-american, drug traffic, biography, based on true story, murder, organized crime, gore, mafia, gangster, new york city, extreme violence, violence, brooklyn new york city, crime epic, tampa]   
4217                                                                                                                                                                                                                                      [puberty, first time]   
883                                                                                                           [con man, biography, fbi agent, overhead camera shot, attempted jailbreak, engagement party, mislaid trust, bank fraud, inspired by a true story]   
3866                            

In [24]:
# 적절치 못한 영화도 간간히 석여있다.

In [29]:
# 평점에 따라 필터링해서 최종 추천하는 방식으로 변경
movies_df[['title','vote_average','vote_count']].sort_values('vote_average', ascending = False).head(10)

title  vote_average  vote_count
3519          Stiff Upper Lips          10.0           1
4247     Me You and Five Bucks          10.0           2
4045     Dancer, Texas Pop. 81          10.0           1
4662            Little Big Top          10.0           1
3992                 Sardaarji           9.5           2
2386            One Man's Hero           9.3           2
2970        There Goes My Baby           8.5           2
1881  The Shawshank Redemption           8.5        8205
2796     The Prisoner of Zenda           8.4          11
3337             The Godfather           8.4        5893

In [30]:
# count가 매우 적은 영화들이 있어서 왜곡된 평점으로 볼 수 있으므로 평점에 평가 횟수를 반영할 수 있는 새로운 평가 방식이 필요하다.

가중평점 = (v/(v+m)) * R + (m/(v+m)) * C
- v: 개별 영화에 평점을 부여한 횟수
- m: 평점을 부여하기 위한 최소 투표 횟수
- R: 개별 영화에 대한 평균 평점
- C: 전체 영화에 대한 평균 평점

In [32]:
v = movies_df['vote_count']
R = movies_df['vote_average']

C = movies_df['vote_average'].mean()
m = movies_df['vote_count'].quantile(0.6) # 전체 투표에서 상위 60%에 해당하는 횟수를 기준으로
print('C:',C, 'm:',m)

C: 6.092171559442011 m: 370.1999999999998


In [38]:
percentile = 0.6
C = movies_df['vote_average'].mean()
m = movies_df['vote_count'].quantile(percentile)

def weighted_vote_average(record):
    v = record['vote_count']
    R = record['vote_average']
    
    return  (v/(v+m)) * R + (m/(v+m)) * C

movies['weighted_vote'] = movies.apply(weighted_vote_average, axis=1)

movies[['title','vote_average','weighted_vote','vote_count']].sort_values('weighted_vote',ascending=False)[:10]

title  vote_average  weighted_vote  vote_count
1881  The Shawshank Redemption           8.5       8.396052        8205
3337             The Godfather           8.4       8.263591        5893
662                 Fight Club           8.3       8.216455        9413
3232              Pulp Fiction           8.3       8.207102        8428
65             The Dark Knight           8.2       8.136930       12002
1818          Schindler's List           8.3       8.126069        4329
3865                  Whiplash           8.3       8.123248        4254
809               Forrest Gump           8.2       8.105954        7927
2294             Spirited Away           8.3       8.105867        3840
2731    The Godfather: Part II           8.3       8.079586        3338

In [45]:
# find_sim_movie() 함수 변경

def find_sim_movie(df, sorted_ind, title_name, top_n):
    
    title_movie = df[df['title'] == title_name]
    title_index = title_movie.index.values
    
    # top_n의 2배에 해당하는 장르 유사성이 높은 인덱스 추출
    similar_indexes = sorted_ind[title_index, :(top_n*2)]
    similar_indexes = similar_indexes.reshape(-1)
    
    # 기준 영화 인덱스는 제외
    similar_indexes = similar_indexes[similar_indexes != title_index]
    
    # top_n의 2배에 해당하는 후보군에서 weighted_vote가 높은 순으로 top_n만큼 추출
    return df.iloc[similar_indexes].sort_values('weighted_vote', ascending=False)[:top_n]

In [46]:
similar_movies = find_sim_movie(movies, genre_sim_sorted_idx, 'The Godfather', 10)
similar_movies[['title','vote_average','weighted_vote']]

title  vote_average  weighted_vote
2731       The Godfather: Part II           8.3       8.079586
1847                   GoodFellas           8.2       7.976937
3866                  City of God           8.1       7.759693
1663  Once Upon a Time in America           8.2       7.657811
883           Catch Me If You Can           7.7       7.557097
281             American Gangster           7.4       7.141396
4041              This Is England           7.4       6.739664
1149              American Hustle           6.8       6.717525
1243                 Mean Streets           7.2       6.626569
2839                     Rounders           6.9       6.530427