In [1]:
# 협업 필터링 기반의 영화 추천을 위해서는 사용자가 영화의 평점을 매긴 사용자-영화 평점 행렬 데이터 세트가 필요

In [1]:
import pandas as pd
import numpy as np

movies = pd.read_csv('movies.csv')
ratings = pd.read_csv('ratings.csv')
print(movies.shape)
print(ratings.shape)

(9742, 3)
(100836, 4)


In [2]:
movies.head()

movieId                               title  \
0        1                    Toy Story (1995)   
1        2                      Jumanji (1995)   
2        3             Grumpier Old Men (1995)   
3        4            Waiting to Exhale (1995)   
4        5  Father of the Bride Part II (1995)   

                                        genres  
0  Adventure|Animation|Children|Comedy|Fantasy  
1                   Adventure|Children|Fantasy  
2                               Comedy|Romance  
3                         Comedy|Drama|Romance  
4                                       Comedy

In [3]:
ratings.head()

userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [4]:
ratings.drop('timestamp', axis=1, inplace=True)

In [5]:
ratings_matrix = ratings.pivot_table('rating',index='userId',columns='movieId')

In [6]:
ratings_matrix

movieId  1       2       3       4       5       6       7       8       \
userId                                                                    
1           4.0     NaN     4.0     NaN     NaN     4.0     NaN     NaN   
2           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
5           4.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
...         ...     ...     ...     ...     ...     ...     ...     ...   
606         2.5     NaN     NaN     NaN     NaN     NaN     2.5     NaN   
607         4.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
608         2.5     2.0     2.0     NaN     NaN     NaN     NaN     NaN   
609         3.0     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
610         5.0     NaN     NaN     NaN     NaN     5.0     NaN     NaN   

movieId  9       10      ...  193565  193567  193571  193573  193579  193581  \
userId                   ...                                                   
1           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
2           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
3           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
4           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
5           NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
...         ...     ...  ...     ...     ...     ...     ...     ...     ...   
606         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
607         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
608         NaN     4.0  ...     NaN     NaN     NaN     NaN     NaN     NaN   
609         NaN     4.0  ...     NaN     NaN     NaN     NaN     NaN     NaN   
610         NaN     NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   

movieId  193583  193585  193587  193609  
userId                                   
1           NaN     NaN     NaN     NaN  
2           NaN     NaN     NaN     NaN  
3           NaN     NaN     NaN     NaN  
4           NaN     NaN     NaN     NaN  
5           NaN     NaN     NaN     NaN  
...         ...     ...     ...     ...  
606         NaN     NaN     NaN     NaN  
607         NaN     NaN     NaN     NaN  
608         NaN     NaN     NaN     NaN  
609         NaN     NaN     NaN     NaN  
610         NaN     NaN     NaN     NaN  

[610 rows x 9724 columns]

In [7]:
rating_movies = pd.merge(ratings, movies, on='movieId')
rating_movies

userId  movieId  rating                             title  \
0            1        1     4.0                  Toy Story (1995)   
1            5        1     4.0                  Toy Story (1995)   
2            7        1     4.5                  Toy Story (1995)   
3           15        1     2.5                  Toy Story (1995)   
4           17        1     4.5                  Toy Story (1995)   
...        ...      ...     ...                               ...   
100831     610   160341     2.5                  Bloodmoon (1997)   
100832     610   160527     4.5  Sympathy for the Underdog (1971)   
100833     610   160836     3.0                     Hazard (2005)   
100834     610   163937     3.5                Blair Witch (2016)   
100835     610   163981     3.5                         31 (2016)   

                                             genres  
0       Adventure|Animation|Children|Comedy|Fantasy  
1       Adventure|Animation|Children|Comedy|Fantasy  
2       Adventure|Animation|Children|Comedy|Fantasy  
3       Adventure|Animation|Children|Comedy|Fantasy  
4       Adventure|Animation|Children|Comedy|Fantasy  
...                                             ...  
100831                              Action|Thriller  
100832                           Action|Crime|Drama  
100833                        Action|Drama|Thriller  
100834                              Horror|Thriller  
100835                                       Horror  

[100836 rows x 5 columns]

In [8]:
ratings_matrix = rating_movies.pivot_table('rating',index='userId',columns='title')
ratings_matrix

title   '71 (2014)  'Hellboy': The Seeds of Creation (2004)  \
userId                                                        
1              NaN                                      NaN   
2              NaN                                      NaN   
3              NaN                                      NaN   
4              NaN                                      NaN   
5              NaN                                      NaN   
...            ...                                      ...   
606            NaN                                      NaN   
607            NaN                                      NaN   
608            NaN                                      NaN   
609            NaN                                      NaN   
610            4.0                                      NaN   

title   'Round Midnight (1986)  'Salem's Lot (2004)  \
userId                                                
1                          NaN                  NaN   
2                          NaN                  NaN   
3                          NaN                  NaN   
4                          NaN                  NaN   
5                          NaN                  NaN   
...                        ...                  ...   
606                        NaN                  NaN   
607                        NaN                  NaN   
608                        NaN                  NaN   
609                        NaN                  NaN   
610                        NaN                  NaN   

title   'Til There Was You (1997)  'Tis the Season for Love (2015)  \
userId                                                               
1                             NaN                              NaN   
2                             NaN                              NaN   
3                             NaN                              NaN   
4                             NaN                              NaN   
5                             NaN                              NaN   
...                           ...                              ...   
606                           NaN                              NaN   
607                           NaN                              NaN   
608                           NaN                              NaN   
609                           NaN                              NaN   
610                           NaN                              NaN   

title   'burbs, The (1989)  'night Mother (1986)  (500) Days of Summer (2009)  \
userId                                                                          
1                      NaN                   NaN                          NaN   
2                      NaN                   NaN                          NaN   
3                      NaN                   NaN                          NaN   
4                      NaN                   NaN                          NaN   
5                      NaN                   NaN                          NaN   
...                    ...                   ...                          ...   
606                    NaN                   NaN                          NaN   
607                    NaN                   NaN                          NaN   
608                    NaN                   NaN                          NaN   
609                    NaN                   NaN                          NaN   
610                    NaN                   NaN                          3.5   

title   *batteries not included (1987)  ...  Zulu (2013)  [REC] (2007)  \
userId                                  ...                              
1                                  NaN  ...          NaN           NaN   
2                                  NaN  ...          NaN           NaN   
3                                  NaN  ...          NaN           NaN   
4                                  NaN  ...          NaN           NaN   
5                                  NaN  ...          Na

In [9]:
rating_movies[rating_movies['title']=="'71 (2014)"]

userId  movieId  rating       title                     genres
100803     610   117867     4.0  '71 (2014)  Action|Drama|Thriller|War

In [10]:
ratings_matrix.fillna(0, inplace=True)

In [11]:
ratings_matrix

title   '71 (2014)  'Hellboy': The Seeds of Creation (2004)  \
userId                                                        
1              0.0                                      0.0   
2              0.0                                      0.0   
3              0.0                                      0.0   
4              0.0                                      0.0   
5              0.0                                      0.0   
...            ...                                      ...   
606            0.0                                      0.0   
607            0.0                                      0.0   
608            0.0                                      0.0   
609            0.0                                      0.0   
610            4.0                                      0.0   

title   'Round Midnight (1986)  'Salem's Lot (2004)  \
userId                                                
1                          0.0                  0.0   
2                          0.0                  0.0   
3                          0.0                  0.0   
4                          0.0                  0.0   
5                          0.0                  0.0   
...                        ...                  ...   
606                        0.0                  0.0   
607                        0.0                  0.0   
608                        0.0                  0.0   
609                        0.0                  0.0   
610                        0.0                  0.0   

title   'Til There Was You (1997)  'Tis the Season for Love (2015)  \
userId                                                               
1                             0.0                              0.0   
2                             0.0                              0.0   
3                             0.0                              0.0   
4                             0.0                              0.0   
5                             0.0                              0.0   
...                           ...                              ...   
606                           0.0                              0.0   
607                           0.0                              0.0   
608                           0.0                              0.0   
609                           0.0                              0.0   
610                           0.0                              0.0   

title   'burbs, The (1989)  'night Mother (1986)  (500) Days of Summer (2009)  \
userId                                                                          
1                      0.0                   0.0                          0.0   
2                      0.0                   0.0                          0.0   
3                      0.0                   0.0                          0.0   
4                      0.0                   0.0                          0.0   
5                      0.0                   0.0                          0.0   
...                    ...                   ...                          ...   
606                    0.0                   0.0                          0.0   
607                    0.0                   0.0                          0.0   
608                    0.0                   0.0                          0.0   
609                    0.0                   0.0                          0.0   
610                    0.0                   0.0                          3.5   

title   *batteries not included (1987)  ...  Zulu (2013)  [REC] (2007)  \
userId                                  ...                              
1                                  0.0  ...          0.0           0.0   
2                                  0.0  ...          0.0           0.0   
3                                  0.0  ...          0.0           0.0   
4                                  0.0  ...          0.0           0.0   
5                                  0.0  ...          0.

In [12]:
ratings_matrix_T = ratings_matrix.transpose()
ratings_matrix_T

userId                                     1    2    3    4    5    6    7    \
title                                                                          
'71 (2014)                                 0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'Hellboy': The Seeds of Creation (2004)    0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'Round Midnight (1986)                     0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'Salem's Lot (2004)                        0.0  0.0  0.0  0.0  0.0  0.0  0.0   
'Til There Was You (1997)                  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
...                                        ...  ...  ...  ...  ...  ...  ...   
eXistenZ (1999)                            0.0  0.0  0.0  0.0  0.0  0.0  0.0   
xXx (2002)                                 0.0  0.0  0.0  0.0  0.0  0.0  0.0   
xXx: State of the Union (2005)             0.0  0.0  0.0  0.0  0.0  0.0  0.0   
¡Three Amigos! (1986)                      4.0  0.0  0.0  0.0  0.0  0.0  0.0   
À nous la liberté (Freedom for Us) (1931)  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

userId                                     8    9    10   ...  601  602  603  \
title                                                     ...                  
'71 (2014)                                 0.0  0.0  0.0  ...  0.0  0.0  0.0   
'Hellboy': The Seeds of Creation (2004)    0.0  0.0  0.0  ...  0.0  0.0  0.0   
'Round Midnight (1986)                     0.0  0.0  0.0  ...  0.0  0.0  0.0   
'Salem's Lot (2004)                        0.0  0.0  0.0  ...  0.0  0.0  0.0   
'Til There Was You (1997)                  0.0  0.0  0.0  ...  0.0  0.0  0.0   
...                                        ...  ...  ...  ...  ...  ...  ...   
eXistenZ (1999)                            0.0  0.0  0.0  ...  0.0  0.0  5.0   
xXx (2002)                                 0.0  1.0  0.0  ...  0.0  0.0  0.0   
xXx: State of the Union (2005)             0.0  0.0  0.0  ...  0.0  0.0  0.0   
¡Three Amigos! (1986)                      0.0  0.0  0.0  ...  0.0  0.0  0.0   
À nous la liberté (Freedom for Us) (1931)  0.0  0.0  0.0  ...  0.0  0.0  0.0   

userId                                     604  605  606  607  608  609  610  
title                                                                         
'71 (2014)                                 0.0  0.0  0.0  0.0  0.0  0.0  4.0  
'Hellboy': The Seeds of Creation (2004)    0.0  0.0  0.0  0.0  0.0  0.0  0.0  
'Round Midnight (1986)                     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
'Salem's Lot (2004)                        0.0  0.0  0.0  0.0  0.0  0.0  0.0  
'Til There Was You (1997)                  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...                                        ...  ...  ...  ...  ...  ...  ...  
eXistenZ (1999)                            0.0  0.0  0.0  0.0  4.5  0.0  0.0  
xXx (2002)                                 0.0  0.0  0.0  0.0  3.5  0.0  2.0  
xXx: State of the Union (2005)             0.0  0.0  0.0  0.0  0.0  0.0  1.5  
¡Three Amigos! (1986)                      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
À nous la liberté (Freedom for Us) (1931)  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[9719 rows x 610 columns]

In [13]:
# 영화간의 코사인 유사도 구하기
from sklearn.metrics.pairwise import cosine_similarity
item_sim = cosine_similarity(ratings_matrix_T, ratings_matrix_T)
item_sim[:2]

array([[1.        , 0.        , 0.        , ..., 0.32732684, 0.        ,
        0.        ],
       [0.        , 1.        , 0.70710678, ..., 0.        , 0.        ,
        0.        ]])

In [14]:
# 영화명 매핑
item_sim_df = pd.DataFrame(data = item_sim, index = ratings_matrix_T.index, columns = ratings_matrix_T.index)

In [15]:
item_sim_df

title                                      '71 (2014)  \
title                                                   
'71 (2014)                                   1.000000   
'Hellboy': The Seeds of Creation (2004)      0.000000   
'Round Midnight (1986)                       0.000000   
'Salem's Lot (2004)                          0.000000   
'Til There Was You (1997)                    0.000000   
...                                               ...   
eXistenZ (1999)                              0.000000   
xXx (2002)                                   0.139431   
xXx: State of the Union (2005)               0.327327   
¡Three Amigos! (1986)                        0.000000   
À nous la liberté (Freedom for Us) (1931)    0.000000   

title                                      'Hellboy': The Seeds of Creation (2004)  \
title                                                                                
'71 (2014)                                                                0.000000   
'Hellboy': The Seeds of Creation (2004)                                   1.000000   
'Round Midnight (1986)                                                    0.707107   
'Salem's Lot (2004)                                                       0.000000   
'Til There Was You (1997)                                                 0.000000   
...                                                                            ...   
eXistenZ (1999)                                                           0.000000   
xXx (2002)                                                                0.000000   
xXx: State of the Union (2005)                                            0.000000   
¡Three Amigos! (1986)                                                     0.000000   
À nous la liberté (Freedom for Us) (1931)                                 0.000000   

title                                      'Round Midnight (1986)  \
title                                                               
'71 (2014)                                               0.000000   
'Hellboy': The Seeds of Creation (2004)                  0.707107   
'Round Midnight (1986)                                   1.000000   
'Salem's Lot (2004)                                      0.000000   
'Til There Was You (1997)                                0.000000   
...                                                           ...   
eXistenZ (1999)                                          0.000000   
xXx (2002)                                               0.000000   
xXx: State of the Union (2005)                           0.000000   
¡Three Amigos! (1986)                                    0.000000   
À nous la liberté (Freedom for Us) (1931)                0.000000   

title                                      'Salem's Lot (2004)  \
title                                                            
'71 (2014)                                            0.000000   
'Hellboy': The Seeds of Creation (2004)               0.000000   
'Round Midnight (1986)                                0.000000   
'Salem's Lot (2004)                                   1.000000   
'Til There Was You (1997)                             0.857493   
...                                                        ...   
eXistenZ (1999)                                       0.000000   
xXx (2002)                                            0.000000   
xXx: State of the Union (2005)                        0.000000   
¡Three Amigos! (1986)                                 0.000000   
À nous la liberté (Freedom for Us) (1931)             0.000000   

title                                      'Til There Was You (1997)  \
title                                                                  
'71 (2014)                                                  0.000000   
'Hellboy': The Seeds of Creation (2004)                     0.000000   
'Round Midnight (1986)                                      0.000000   
'Salem's Lot (2004)   

In [16]:
item_sim_df['Godfather, The (1972)'].sort_values(ascending=False)[:6]

title
Godfather, The (1972)                        1.000000
Godfather: Part II, The (1974)               0.821773
Goodfellas (1990)                            0.664841
One Flew Over the Cuckoo's Nest (1975)       0.620536
Star Wars: Episode IV - A New Hope (1977)    0.595317
Fargo (1996)                                 0.588614
Name: Godfather, The (1972), dtype: float64

In [17]:
item_sim_df['Inception (2010)'].sort_values(ascending=False)[1:6]

title
Dark Knight, The (2008)          0.727263
Inglourious Basterds (2009)      0.646103
Shutter Island (2010)            0.617736
Dark Knight Rises, The (2012)    0.617504
Fight Club (1999)                0.615417
Name: Inception (2010), dtype: float64

In [19]:
# 이는 영화 간의 유사도만을 가지고 추천한 것으로, 개인적인 취향을 반영하지 않는다.

#### 최근접 이웃 협업 필터링으로 개인에게 최적화된 영화 추천 구현

In [65]:
def predict_rating(ratings_arr,item_sim_arr):
    ratings_pred = ratings_arr.dot(item_sim_arr)/np.array([np.abs(item_sim_arr).sum(axis=1)])
    return ratings_pred

In [67]:
ratings_pred = predict_rating(ratings_matrix.values,item_sim_df.values)
ratings_pred_matrix = pd.DataFrame(data=ratings_pred, index = ratings_matrix.index, columns = ratings_matrix.columns)

ratings_pred_matrix

title   '71 (2014)  'Hellboy': The Seeds of Creation (2004)  \
userId                                                        
1         0.070345                                 0.577855   
2         0.018260                                 0.042744   
3         0.011884                                 0.030279   
4         0.049145                                 0.277628   
5         0.007278                                 0.066951   
...            ...                                      ...   
606       0.246832                                 1.293006   
607       0.052248                                 0.305255   
608       0.324435                                 1.022541   
609       0.004835                                 0.053593   
610       3.628303                                 1.517918   

title   'Round Midnight (1986)  'Salem's Lot (2004)  \
userId                                                
1                     0.321696             0.227055   
2                     0.018861             0.000000   
3                     0.064437             0.003762   
4                     0.160448             0.206892   
5                     0.041879             0.013880   
...                        ...                  ...   
606                   0.752661             0.935924   
607                   0.180669             0.218834   
608                   0.598467             0.425468   
609                   0.026251             0.000000   
610                   0.833668             0.399443   

title   'Til There Was You (1997)  'Tis the Season for Love (2015)  \
userId                                                               
1                        0.206958                         0.194615   
2                        0.000000                         0.035995   
3                        0.003749                         0.002722   
4                        0.309632                         0.042337   
5                        0.024842                         0.018240   
...                           ...                              ...   
606                      1.032354                         0.407038   
607                      0.179443                         0.115288   
608                      0.349562                         0.494081   
609                      0.002827                         0.015528   
610                      0.310888                         1.117761   

title   'burbs, The (1989)  'night Mother (1986)  (500) Days of Summer (2009)  \
userId                                                                          
1                 0.249883              0.102542                     0.157084   
2                 0.013413              0.002314                     0.032213   
3                 0.014625              0.002085                     0.005666   
4                 0.130048              0.116442                     0.099785   
5                 0.026405              0.018673                     0.021591   
...                    ...                   ...                          ...   
606               0.516819              0.594590                     0.489913   
607               0.165817              0.075548                     0.104890   
608               0.529903              0.227746                     0.480980   
609               0.017849              0.007791                     0.013172   
610               0.567028              0.226168                     1.053823   

title   *batteries not included (1987)  ...  Zulu (2013)  [REC] (2007)  \
userId                                  ...                              
1                             0.178197  ...     0.113608      0.181738   
2                             0.014863  ...     0.015640      0.020855   
3                             0.006272  ...     0.006923      0.011665   
4                             0.097432  ...     0.051269      0.076051   
5                             0.018841  ...     0.00968

In [28]:
# 위 함수를 따로 떼어 분석
ratings_matrix.values.dot(item_sim_df.values)

array([[3.57401145e+01, 2.62758205e+01, 2.34412062e+01, ...,
        7.11052648e+01, 2.67848707e+02, 3.00523758e+01],
       [9.27741787e+00, 1.94363803e+00, 1.37435963e+00, ...,
        1.28216967e+01, 1.60579245e+01, 0.00000000e+00],
       [6.03816699e+00, 1.37681377e+00, 4.69539510e+00, ...,
        4.82422237e+00, 9.52685081e+00, 3.52534038e+00],
       ...,
       [1.64835873e+02, 4.64963218e+01, 4.36088636e+01, ...,
        2.81539882e+02, 4.82420933e+02, 2.91563885e+01],
       [2.45646314e+00, 2.43693265e+00, 1.91286274e+00, ...,
        6.85190203e+00, 1.67575515e+01, 1.39245612e+00],
       [1.84343601e+03, 6.90217759e+01, 6.07474265e+01, ...,
        9.49340955e+02, 5.16649163e+02, 2.39741586e+01]])

In [29]:
ratings_matrix.dot(item_sim_df)

title    '71 (2014)  'Hellboy': The Seeds of Creation (2004)  \
userId                                                         
1         35.740115                                26.275820   
2          9.277418                                 1.943638   
3          6.038167                                 1.376814   
4         24.969347                                12.624132   
5          3.697901                                 3.044372   
...             ...                                      ...   
606      125.408180                                58.794711   
607       26.545820                                13.880356   
608      164.835873                                46.496322   
609        2.456463                                 2.436933   
610     1843.436006                                69.021776   

title   'Round Midnight (1986)  'Salem's Lot (2004)  \
userId                                                
1                    23.441206             4.200928   
2                     1.374360             0.000000   
3                     4.695395             0.069598   
4                    11.691495             3.827885   
5                     3.051645             0.256805   
...                        ...                  ...   
606                  54.844619            17.316328   
607                  13.164895             4.048835   
608                  43.608864             7.871943   
609                   1.912863             0.000000   
610                  60.747426             7.390439   

title   'Til There Was You (1997)  'Tis the Season for Love (2015)  \
userId                                                               
1                        7.826024                        20.971658   
2                        0.000000                         3.878789   
3                        0.141748                         0.293269   
4                       11.708575                         4.562202   
5                        0.939378                         1.965523   
...                           ...                              ...   
606                     39.037921                        43.862402   
607                      6.785530                        12.423381   
608                     13.218490                        53.242084   
609                      0.106886                         1.673291   
610                     11.756080                       120.449754   

title   'burbs, The (1989)  'night Mother (1986)  (500) Days of Summer (2009)  \
userId                                                                          
1               178.026535             85.085722                   144.541322   
2                 9.555780              1.919737                    29.640982   
3                10.419400              1.730442                     5.213261   
4                92.651498             96.619034                    91.817113   
5                18.812218             15.493783                    19.866791   
...                    ...                   ...                          ...   
606             368.202697            493.369503                   450.793312   
607             118.134986             62.687258                    96.514352   
608             377.524286            188.975397                   442.573501   
609              12.716209              6.464997                    12.120116   
610             403.974021            187.666313                   969.675543   

title   *batteries not included (1987)  ...  Zulu (2013)  [REC] (2007)  \
userId                                  ...                              
1                           124.028198  ...    79.163865     97.238015   
2                            10.345093  ...    10.898454     11.158151   
3                             4.365703  ...     4.823781      6.241044   
4                            67.814082  ...    35.725332     40.690702   
5                            13.113867  ..

In [31]:
np.array([np.abs(item_sim_df).sum(axis=1)])

array([[508.07109734,  45.47134351,  72.86766512, ..., 522.73875081,
        914.30133794,  41.71929155]])

In [70]:
abs(item_sim_df).sum()

title
'71 (2014)                                   508.071097
'Hellboy': The Seeds of Creation (2004)       45.471344
'Round Midnight (1986)                        72.867665
'Salem's Lot (2004)                           18.501847
'Til There Was You (1997)                     37.814481
                                                ...    
eXistenZ (1999)                              899.193217
xXx (2002)                                   938.502156
xXx: State of the Union (2005)               522.738751
¡Three Amigos! (1986)                        914.301338
À nous la liberté (Freedom for Us) (1931)     41.719292
Length: 9719, dtype: float64

In [32]:
np.array([np.abs(item_sim_df.values).sum(axis=1)])

array([[508.07109734,  45.47134351,  72.86766512, ..., 522.73875081,
        914.30133794,  41.71929155]])

In [35]:
np.abs(item_sim_df.values).sum(axis=1)

array([508.07109734,  45.47134351,  72.86766512, ..., 522.73875081,
       914.30133794,  41.71929155])

In [61]:
# np.abs(item_sim_df.values).sum(axis=1)로 변경해보자.
def predict_rating(ratings_arr,item_sim_arr):
    ratings_pred = ratings_arr.dot(item_sim_arr)/np.abs(item_sim_df.values).sum(axis=1)
    return ratings_pred

In [62]:
ratings_pred = predict_rating(ratings_matrix.values,item_sim_df.values)
ratings_pred_matrix = pd.DataFrame(data=ratings_pred, index = ratings_matrix.index, columns = ratings_matrix.columns)

ratings_pred_matrix

title   '71 (2014)  'Hellboy': The Seeds of Creation (2004)  \
userId                                                        
1         0.070345                                 0.577855   
2         0.018260                                 0.042744   
3         0.011884                                 0.030279   
4         0.049145                                 0.277628   
5         0.007278                                 0.066951   
...            ...                                      ...   
606       0.246832                                 1.293006   
607       0.052248                                 0.305255   
608       0.324435                                 1.022541   
609       0.004835                                 0.053593   
610       3.628303                                 1.517918   

title   'Round Midnight (1986)  'Salem's Lot (2004)  \
userId                                                
1                     0.321696             0.227055   
2                     0.018861             0.000000   
3                     0.064437             0.003762   
4                     0.160448             0.206892   
5                     0.041879             0.013880   
...                        ...                  ...   
606                   0.752661             0.935924   
607                   0.180669             0.218834   
608                   0.598467             0.425468   
609                   0.026251             0.000000   
610                   0.833668             0.399443   

title   'Til There Was You (1997)  'Tis the Season for Love (2015)  \
userId                                                               
1                        0.206958                         0.194615   
2                        0.000000                         0.035995   
3                        0.003749                         0.002722   
4                        0.309632                         0.042337   
5                        0.024842                         0.018240   
...                           ...                              ...   
606                      1.032354                         0.407038   
607                      0.179443                         0.115288   
608                      0.349562                         0.494081   
609                      0.002827                         0.015528   
610                      0.310888                         1.117761   

title   'burbs, The (1989)  'night Mother (1986)  (500) Days of Summer (2009)  \
userId                                                                          
1                 0.249883              0.102542                     0.157084   
2                 0.013413              0.002314                     0.032213   
3                 0.014625              0.002085                     0.005666   
4                 0.130048              0.116442                     0.099785   
5                 0.026405              0.018673                     0.021591   
...                    ...                   ...                          ...   
606               0.516819              0.594590                     0.489913   
607               0.165817              0.075548                     0.104890   
608               0.529903              0.227746                     0.480980   
609               0.017849              0.007791                     0.013172   
610               0.567028              0.226168                     1.053823   

title   *batteries not included (1987)  ...  Zulu (2013)  [REC] (2007)  \
userId                                  ...                              
1                             0.178197  ...     0.113608      0.181738   
2                             0.014863  ...     0.015640      0.020855   
3                             0.006272  ...     0.006923      0.011665   
4                             0.097432  ...     0.051269      0.076051   
5                             0.018841  ...     0.00968

In [39]:
# 굳이 .values를 인자값으로 해야 할 필요가 있나?
ratings_pred = predict_rating(ratings_matrix,item_sim_df)
ratings_pred_matrix = pd.DataFrame(data=ratings_pred, index = ratings_matrix.index, columns = ratings_matrix.columns)

ratings_pred_matrix

title   '71 (2014)  'Hellboy': The Seeds of Creation (2004)  \
userId                                                        
1         0.070345                                 0.577855   
2         0.018260                                 0.042744   
3         0.011884                                 0.030279   
4         0.049145                                 0.277628   
5         0.007278                                 0.066951   
...            ...                                      ...   
606       0.246832                                 1.293006   
607       0.052248                                 0.305255   
608       0.324435                                 1.022541   
609       0.004835                                 0.053593   
610       3.628303                                 1.517918   

title   'Round Midnight (1986)  'Salem's Lot (2004)  \
userId                                                
1                     0.321696             0.227055   
2                     0.018861             0.000000   
3                     0.064437             0.003762   
4                     0.160448             0.206892   
5                     0.041879             0.013880   
...                        ...                  ...   
606                   0.752661             0.935924   
607                   0.180669             0.218834   
608                   0.598467             0.425468   
609                   0.026251             0.000000   
610                   0.833668             0.399443   

title   'Til There Was You (1997)  'Tis the Season for Love (2015)  \
userId                                                               
1                        0.206958                         0.194615   
2                        0.000000                         0.035995   
3                        0.003749                         0.002722   
4                        0.309632                         0.042337   
5                        0.024842                         0.018240   
...                           ...                              ...   
606                      1.032354                         0.407038   
607                      0.179443                         0.115288   
608                      0.349562                         0.494081   
609                      0.002827                         0.015528   
610                      0.310888                         1.117761   

title   'burbs, The (1989)  'night Mother (1986)  (500) Days of Summer (2009)  \
userId                                                                          
1                 0.249883              0.102542                     0.157084   
2                 0.013413              0.002314                     0.032213   
3                 0.014625              0.002085                     0.005666   
4                 0.130048              0.116442                     0.099785   
5                 0.026405              0.018673                     0.021591   
...                    ...                   ...                          ...   
606               0.516819              0.594590                     0.489913   
607               0.165817              0.075548                     0.104890   
608               0.529903              0.227746                     0.480980   
609               0.017849              0.007791                     0.013172   
610               0.567028              0.226168                     1.053823   

title   *batteries not included (1987)  ...  Zulu (2013)  [REC] (2007)  \
userId                                  ...                              
1                             0.178197  ...     0.113608      0.181738   
2                             0.014863  ...     0.015640      0.020855   
3                             0.006272  ...     0.006923      0.011665   
4                             0.097432  ...     0.051269      0.076051   
5                             0.018841  ...     0.00968

In [71]:
# 위와 같은 예측 평점이 원래의 실제 평점과 얼마나 차이가 있을까? 기존에 평점이 부여된 데이터에 대해서만 오차 정도를 측정해보자.
from sklearn.metrics import mean_squared_error

def get_mse(pred, actual):
    # 실제 평점이 있는 영화만 추출
    pred = pred[actual.nonzero()].flatten() # numpy  모듈의 nonzero 함수는 요소들 중 0이 아닌 값들의 index 들을 반환해 주는 함수
    actual = actual[actual.nonzero()].flatten()
    return mean_squared_error(pred,actual)

In [72]:
print('아이템 기반 모든 최근접 이웃 MSE: ', get_mse(ratings_pred, ratings_matrix.values))

아이템 기반 모든 최근접 이웃 MSE:  9.895354759094706


In [73]:
# 위 함수 분석
pred = ratings_pred[ratings_matrix.values.nonzero()].flatten()
pred

array([0.2855597 , 1.08359021, 0.35404974, ..., 2.57350896, 1.08329872,
       1.81609065])

In [82]:
ratings_matrix.values.nonzero()

(array([  0,   0,   0, ..., 609, 609, 609], dtype=int64),
 array([  48,   66,  202, ..., 9712, 9715, 9716], dtype=int64))

In [80]:
ratings_pred[ratings_matrix.values.nonzero()]

array([0.2855597 , 1.08359021, 0.35404974, ..., 2.57350896, 1.08329872,
       1.81609065])

In [90]:
ratings_pred[ratings_matrix.values.nonzero()].flatten()

array([0.2855597 , 1.08359021, 0.35404974, ..., 2.57350896, 1.08329872,
       1.81609065])

In [86]:
# 참고 nonzero 함수
a=np.array([[1, 0, 7], [8, 1, 0], [1, 0, 0]])
a

array([[1, 0, 7],
       [8, 1, 0],
       [1, 0, 0]])

In [87]:
np.nonzero(a)

(array([0, 0, 1, 1, 2], dtype=int64), array([0, 2, 0, 1, 0], dtype=int64))

In [89]:
a.nonzero()

(array([0, 0, 1, 1, 2], dtype=int64), array([0, 2, 0, 1, 0], dtype=int64))

In [88]:
# a 의 요소 중 (0,0), (0, 2), (1, 0), (1, 1), (2, 0) 에 위치한 요소들이 0 이 아닌 값들을 갖고 있다는 것을 보여주는 것

In [92]:
# MSE가 9.895이므로 MSE를 감소시키는 방향으로 개선해보자.
# 특정 영화와 가장 비슷한 유사도를 가지는 영화에 대해서만 유사도 벡터를 적용하는 함수로 변경

def predict_rating_topsim(ratings_arr,item_sim_arr, n=20):
    # 사용자-아이템 평점 행렬 크기만큼 0으로 채운 예측 행렬 초기화
    pred = np.zeros(ratings_arr.shape)
    
    # 사용자-아이템 평점 행렬의 열 크기만큼 루프 수행
    for col in range(ratings_arr.shape[1]):
        # 유사도 행렬에서 유사도가 큰 순으로 n개 데이터 행렬의 인덱스 반환
        top_n_items = [np.argsort(item_sim_arr[:,col])[:-n-1:-1]]
        # 개인화된 예측 평점 계산
        for row in range(ratings_arr.shape[0]):
            pred[row,col] = item_sim_arr[col,:][top_n_items].dot(ratings_arr[row,:][top_n_items].T)
            pred[row,col] /= np.sum(np.abs(item_sim_arr[col,:][top_n_items]))
            
    return pred

In [93]:
ratings_pred = predict_rating_topsim(ratings_matrix.values , item_sim_df.values, n=20)
print('아이템 기반 인접 TOP-20 이웃 MSE: ', get_mse(ratings_pred, ratings_matrix.values ))


# 계산된 예측 평점 데이터는 DataFrame으로 재생성
ratings_pred_matrix = pd.DataFrame(data=ratings_pred, index= ratings_matrix.index,
                                   columns = ratings_matrix.columns)

<ipython-input-92-cea71098794b>:13: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  pred[row,col] = item_sim_arr[col,:][top_n_items].dot(ratings_arr[row,:][top_n_items].T)
<ipython-input-92-cea71098794b>:14: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  pred[row,col] /= np.sum(np.abs(item_sim_arr[col,:][top_n_items]))


아이템 기반 인접 TOP-20 이웃 MSE:  3.6949696289030554


In [94]:
user_rating_id = ratings_matrix.loc[9, :]
user_rating_id[ user_rating_id > 0].sort_values(ascending=False)[:10]

title
Adaptation (2002)                                                                 5.0
Austin Powers in Goldmember (2002)                                                5.0
Lord of the Rings: The Fellowship of the Ring, The (2001)                         5.0
Lord of the Rings: The Two Towers, The (2002)                                     5.0
Producers, The (1968)                                                             5.0
Citizen Kane (1941)                                                               5.0
Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark) (1981)    5.0
Back to the Future (1985)                                                         5.0
Glengarry Glen Ross (1992)                                                        4.0
Sunset Blvd. (a.k.a. Sunset Boulevard) (1950)                                     4.0
Name: 9, dtype: float64

In [95]:
# 이 사람에게 아이템 기반 협업 필터링을 통해 영화 추천
# 이미 평점을 준 영화를 제외하고 추천

# 평점을 주지 않은 영화를 리스트 객체로 반환하는 함수인 get_unseen_moives()

def get_unseen_movies(ratings_matrix, userId):
    # userId로 입력받은 사용자의 모든 영화정보 추출하여 Series로 반환함. 
    # 반환된 user_rating 은 영화명(title)을 index로 가지는 Series 객체임. 
    user_rating = ratings_matrix.loc[userId,:]
    
    # user_rating이 0보다 크면 기존에 관람한 영화임. 대상 index를 추출하여 list 객체로 만듬
    already_seen = user_rating[ user_rating > 0].index.tolist()
    
    # 모든 영화명을 list 객체로 만듬. 
    movies_list = ratings_matrix.columns.tolist()
    
    # list comprehension으로 already_seen에 해당하는 movie는 movies_list에서 제외함. 
    unseen_list = [ movie for movie in movies_list if movie not in already_seen]
    
    return unseen_list

In [102]:
user_rating = ratings_matrix.loc[9,:]
user_rating

title
'71 (2014)                                   0.0
'Hellboy': The Seeds of Creation (2004)      0.0
'Round Midnight (1986)                       0.0
'Salem's Lot (2004)                          0.0
'Til There Was You (1997)                    0.0
                                            ... 
eXistenZ (1999)                              0.0
xXx (2002)                                   1.0
xXx: State of the Union (2005)               0.0
¡Three Amigos! (1986)                        0.0
À nous la liberté (Freedom for Us) (1931)    0.0
Name: 9, Length: 9719, dtype: float64

In [104]:
already_seen = user_rating[ user_rating > 0].index.tolist()
already_seen

['Adaptation (2002)',
 'Any Given Sunday (1999)',
 'Austin Powers in Goldmember (2002)',
 'Back to the Future (1985)',
 'Back to the Future Part II (1989)',
 'Back to the Future Part III (1990)',
 'Blind Date (1984)',
 'Body of Evidence (1993)',
 'Citizen Kane (1941)',
 'Clerks (1994)',
 'Die Another Day (2002)',
 'Duellists, The (1977)',
 'Elling (2001)',
 'Gangs of New York (2002)',
 'Ghost Dog: The Way of the Samurai (1999)',
 'Glengarry Glen Ross (1992)',
 'Godfather: Part III, The (1990)',
 'I Spit on Your Grave (Day of the Woman) (1978)',
 'Ice Age (2002)',
 'King of Comedy, The (1983)',
 'Last Seduction, The (1994)',
 'Last Supper, The (1995)',
 'Lawnmower Man, The (1992)',
 'Lord of the Rings: The Fellowship of the Ring, The (2001)',
 'Lord of the Rings: The Two Towers, The (2002)',
 'Making Mr. Right (1987)',
 'Minority Report (2002)',
 'Paper, The (1994)',
 'Party Girl (1995)',
 'Phantasm (1979)',
 'Producers, The (1968)',
 'Prom Night (1980)',
 'Pumpkin (2002)',
 'Quicksilve

In [106]:
movies_list = ratings_matrix.columns.tolist()
movies_list

["'71 (2014)",
 "'Hellboy': The Seeds of Creation (2004)",
 "'Round Midnight (1986)",
 "'Salem's Lot (2004)",
 "'Til There Was You (1997)",
 "'Tis the Season for Love (2015)",
 "'burbs, The (1989)",
 "'night Mother (1986)",
 '(500) Days of Summer (2009)',
 '*batteries not included (1987)',
 '...All the Marbles (1981)',
 '...And Justice for All (1979)',
 '00 Schneider - Jagd auf Nihil Baxter (1994)',
 '1-900 (06) (1994)',
 '10 (1979)',
 '10 Cent Pistol (2015)',
 '10 Cloverfield Lane (2016)',
 '10 Items or Less (2006)',
 '10 Things I Hate About You (1999)',
 '10 Years (2011)',
 '10,000 BC (2008)',
 '100 Girls (2000)',
 '100 Streets (2016)',
 '101 Dalmatians (1996)',
 '101 Dalmatians (One Hundred and One Dalmatians) (1961)',
 "101 Dalmatians II: Patch's London Adventure (2003)",
 '101 Reykjavik (101 Reykjavík) (2000)',
 '102 Dalmatians (2000)',
 '10th & Wolf (2006)',
 '10th Kingdom, The (2000)',
 '10th Victim, The (La decima vittima) (1965)',
 '11\'09"01 - September 11 (2002)',
 '11:14 (2

In [107]:
unseen_list = [ movie for movie in movies_list if movie not in already_seen]
unseen_list

["'71 (2014)",
 "'Hellboy': The Seeds of Creation (2004)",
 "'Round Midnight (1986)",
 "'Salem's Lot (2004)",
 "'Til There Was You (1997)",
 "'Tis the Season for Love (2015)",
 "'burbs, The (1989)",
 "'night Mother (1986)",
 '(500) Days of Summer (2009)',
 '*batteries not included (1987)',
 '...All the Marbles (1981)',
 '...And Justice for All (1979)',
 '00 Schneider - Jagd auf Nihil Baxter (1994)',
 '1-900 (06) (1994)',
 '10 (1979)',
 '10 Cent Pistol (2015)',
 '10 Cloverfield Lane (2016)',
 '10 Items or Less (2006)',
 '10 Things I Hate About You (1999)',
 '10 Years (2011)',
 '10,000 BC (2008)',
 '100 Girls (2000)',
 '100 Streets (2016)',
 '101 Dalmatians (1996)',
 '101 Dalmatians (One Hundred and One Dalmatians) (1961)',
 "101 Dalmatians II: Patch's London Adventure (2003)",
 '101 Reykjavik (101 Reykjavík) (2000)',
 '102 Dalmatians (2000)',
 '10th & Wolf (2006)',
 '10th Kingdom, The (2000)',
 '10th Victim, The (La decima vittima) (1965)',
 '11\'09"01 - September 11 (2002)',
 '11:14 (2

In [108]:
def recomm_movie_by_userid(pred_df, userId, unseen_list, top_n=10):
    # 예측 평점 DataFrame에서 사용자id index와 unseen_list로 들어온 영화명 컬럼을 추출하여
    # 가장 예측 평점이 높은 순으로 정렬함. 
    recomm_movies = pred_df.loc[userId, unseen_list].sort_values(ascending=False)[:top_n]
    return recomm_movies
    
# 사용자가 관람하지 않는 영화명 추출   
unseen_list = get_unseen_movies(ratings_matrix, 9)

# 아이템 기반의 인접 이웃 협업 필터링으로 영화 추천 
recomm_movies = recomm_movie_by_userid(ratings_pred_matrix, 9, unseen_list, top_n=10)

# 평점 데이타를 DataFrame으로 생성. 
recomm_movies = pd.DataFrame(data=recomm_movies.values,index=recomm_movies.index,columns=['pred_score'])
recomm_movies

pred_score
title                                                         
Shrek (2001)                                          0.866202
Spider-Man (2002)                                     0.857854
Last Samurai, The (2003)                              0.817473
Indiana Jones and the Temple of Doom (1984)           0.816626
Matrix Reloaded, The (2003)                           0.800990
Harry Potter and the Sorcerer's Stone (a.k.a. H...    0.765159
Gladiator (2000)                                      0.740956
Matrix, The (1999)                                    0.732693
Pirates of the Caribbean: The Curse of the Blac...    0.689591
Lord of the Rings: The Return of the King, The ...    0.676711